#ifndef SOFTLOQ_WHATWG_INFRA_VERSION_HPP
#define SOFTLOQ_WHATWG_INFRA_VERSION_HPP

#define SOFTLOQ_WHATWG_INFRA_VERSION_YEAR 2025
#define SOFTLOQ_WHATWG_INFRA_VERSION_MONTH 11
#define SOFTLOQ_WHATWG_INFRA_VERSION_DAY 24

#define SOFTLOQ_WHATWG_INFRA_VERSION_NUMBER\
    (SOFTLOQ_WHATWG_INFRA_VERSION_YEAR * 10000 +\
    SOFTLOQ_WHATWG_INFRA_VERSION_MONTH * 100 +\
    SOFTLOQ_WHATWG_INFRA_VERSION_DAY)
#define SOFTLOQ_WHATWG_INFRA_VERSION_STRING "2025-11-24"

#endif // SOFTLOQ_WHATWG_INFRA_VERSION_HPP
